### ISSUE TITLE
How many GPUs are required for this task?

### ISSUE THREAD

**Issue by shibangfan** [fylwen/HTT#1]

**Comment by fylwen** [comment]
Hello, for training, we train on 2 GTX 1080Ti GPUs by assigning each GPU a sample of sequence length T=128, for inference 1 GPU is enough.

**Comment by ArenaGrenade** [comment]
Hey @fylwen  when you say 1 GPU for inference, what is the approximate memory requirement like? Do you make use of the full 10 GB on offer with the 1080Ti?

**Comment by fylwen** [comment]
Hello.
For the inference stage after training, 10 GB is enough for running with batch size=1. You can reduce the batch size in the inference stage, if there is out of memory issue.
