### ISSUE TITLE
Do you have camera real-time testing code?

### ISSUE THREAD

**Issue by zy1996829** [fylwen/HTT#2]
Hello, I want to use my camera to test.Do you have real-time demo? Thanks!

**Comment by fylwen** [comment]
Hello. 

For using your camera to test, the image sequence is necessary as input for the HTT model (cf. https://github.com/fylwen/HTT/blob/main/models/htt.py#L117 ), where _batch_flatten[TransQueries.IMAGE]_ corresponds to the per-frame image.

To prepare the batch you may refer to the code at https://github.com/fylwen/HTT/blob/main/datasets/seqset_htt.py  
Note that images are normalized, cf. https://github.com/fylwen/HTT/blob/main/datasets/seqset_htt.py#L185
