### ISSUE TITLE
Inference In wild video?

### ISSUE THREAD

**Issue by timegoby** [fylwen/HTT#3]
Hello, thanks for share !
I wonder if the model only support first-person view?
And is there any code for inferencing in wild video?

**Comment by fylwen** [comment]
Hello. Thank you for your interest in HTT.

In the original paper, we train and test HTT on egocentric view data (i.e., FPHA and H2O datasets), where the FPHA and H2O are with separate pre-trained HTT.

You can try to train and test HTT on third-person view data, I consider HTT can work in third-person view datasets.


To test on in-the-wild data, you may need to process in-the-wild video, by referring to https://github.com/fylwen/HTT/blob/main/eval.py and https://github.com/fylwen/HTT/blob/main/datasets/seqset_htt.py (data processing).

**Comment by timegoby** [comment]
get it, thanks again.
